# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Metropolis sampler for random walks using Rcpp.
#' @description A Metropolis sampler for random walks using Rcpp(in homework 9).
#' @param sigma variance of the proposal distribution (double)
#' @param x0 the initial position (double)
#' @param N the length of chain (integer)
#' @return a list consists of a generated chain and accept rate of the sampler
#' @examples
#' \dontrun{
#' N = 2000
#' sigma = c(.05, .5, 2, 16)
#' x0 = 25
#' rw1.c = MetropolisCpp(sigma[1],x0,N)
#' rw2.c = MetropolisCpp(sigma[2],x0,N)
#' rw3.c = MetropolisCpp(sigma[3],x0,N)
#' rw4.c = MetropolisCpp(sigma[4],x0,N)
#' #number of candidate points rejected
#' Rej = cbind(rw1.c$k, rw2.c$k, rw3.c$k, rw4.c$k)
#' Acc = round((N-Rej)/N,4)
#' rownames(Acc) = "Accept rates"
#' colnames(Acc) = paste("sigma",sigma)
#' Acc
#' }
#' @export
MetropolisCpp <- function(sigma, x0, N) {
    .Call(`_mypackage_MetropolisCpp`, sigma, x0, N)
}

rcpp_hello_world <- function() {
    .Call(`_mypackage_rcpp_hello_world`)
}

